apiVersion: v1
kind: Service
metadata:
  name: simple-server
  labels:
    name: simple-server
spec:
  ports:
    # the port that this service should serve on
  - port: 9090
    targetPort: 9090
  selector:
    name: simple-server
  # externalIPs:
  # - 1.1.1.1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-server
  labels:
    name: simple-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: simple-server
    spec:
      containers:
      - name: simple-server
        image: dongyiyang/simpleserver:0.1
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 9090
