apiVersion: v1
kind: ReplicationController
metadata:
  name: simple-server
  labels:
    name: simple-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: simple-server
    spec:
      containers:
      - name: simple-server
        image: dongyiyang/simpleserver:0.1
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
        ports:
        - containerPort: 9090
