apiVersion: v1
kind: Pod
metadata:
  name: simple-server
  labels:
    name: simple-server
spec:
  containers:
  - name: simpleserver
    image: dongyiyang/simpleserver:0.1
    command:
      - /bin/main
    args:
      - --v=3
  restartPolicy: Always